workflows:
  build-android:
    name: Build Android APK
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        PROJECT_DIR: "news_admin"
    scripts:
      - name: Get Flutter packages
        script: |
          cd $PROJECT_DIR
          flutter pub get
      - name: Build APK
        script: |
          cd $PROJECT_DIR
          flutter build apk --release
    artifacts:
      - news_admin/build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - ramijwar4@gmail.com
